# Basics- Manipulating row, columns, indices, etc. using pandas

We start with importing some data.

In [65]:
import pandas as pd

In [66]:
df = pd.read_excel("data/Mineral data.xlsx")

df

,mineral,oxygens,sample,no.,SiO2,TiO2,Al2O3,Cr2O3,FeO,MnO,...,Al,Cr,Fe,Mn,Ni,Mg,Ca,Na,K,total cations
0,ol,4,chd#2,1,42.51,0.04,0.07,0.04,0.18,0.00,...,0.002,0.001,0.004,0.000,0.000,1.944,0.040,0.000,0.000,2.995
1,ol,4,chd#2,9,42.16,0.10,0.06,0.20,3.14,0.07,...,0.002,0.004,0.063,0.001,0.001,1.910,0.006,0.000,0.000,2.992
2,cpx,6,chd#2,4,52.33,2.00,4.09,0.81,0.32,0.10,...,0.172,0.023,0.010,0.003,0.000,1.037,0.805,0.001,0.000,3.977
3,cpx,6,chd#2,6,51.54,1.74,5.72,0.56,0.67,0.09,...,0.241,0.016,0.020,0.003,0.000,1.019,0.795,0.003,0.000,3.984
4,opx,6,chd#2,8,57.09,0.22,0.76,0.48,1.92,0.08,...,0.031,0.013,0.055,0.002,0.001,1.897,0.025,0.001,0.000,4.002
5,opx,6,chd#2,10,59.19,0.19,0.63,0.51,0.67,0.20,...,0.025,0.014,0.019,0.006,0.001,1.906,0.024,0.001,0.000,3.988
6,cpx,6,chd#2,11,58.33,0.30,0.98,0.53,0.33,0.14,...,0.039,0.014,0.009,0.004,0.000,1.754,0.182,0.001,0.000,3.989
7,cpx,6,chd#2,12,53.87,1.10,3.09,0.51,0.21,0.08,...,0.129,0.014,0.006,0.002,0.000,1.164,0.731,0.000,0.000,3.988
8,fs,8,chd#2,3,47.10,0.06,32.39,0.01,0.21,0.00,...,1.754,0.000,0.008,0.000,0.000,0.073,0.885,0.143,0.000,5.029
9,fs,8,chd#2,5,47.72,0.06,31.87,0.01,0.71,0.03,...,1.732,0.000,0.027,0.001,0.000,0.040,0.834,0.190,0.000,5.026
10,ol,4,chd#3,15,42.72,0.05,1.08,0.11,0.37,0.01,...,0.030,0.002,0.007,0.000,0.000,1.904,0.017,0.024,0.000,2.991
11,ol,4,chd#3,17,42.83,0.03,0.11,0.16,0.45,0.00,...,0.003,0.003,0.009,0.000,0.000,1.961,0.012,0.000,0.000,2.992
12,ol,4,chd#3,18,40.43,0.02,0.03,0.11,11.16,0.00,...,0.001,0.002,0.233,0.000,0.000,1.733,0.009,0.000,0.000,2.989
13,ol,4,chd#3,21,42.46,0.05,0.27,0.10,0.32,0.03,...,0.008,0.002,0.006,0.001,0.000,1.951,0.014,0.000,0.000,2.989
14,cpx,6,chd#3,16,45.09,0.56,22.45,0.36,3.62,0.00,...,0.928,0.010,0.106,0.000,0.000,0.720,0.560,0.033,0.000,3.952
15,cpx,6,chd#3,19,46.72,1.91,22.05,0.76,0.64,0.00,...,0.922,0.021,0.019,0.000,0.001,0.388,0.742,0.034,0.000,3.837
16,fsp/mes,8,chd#3,20,46.36,0.67,27.52,0.26,0.53,0.00,...,1.516,0.010,0.021,0.000,0.005,0.330,0.947,0.053,0.000,5.073
17,fsp/mes,8,chd#3,25,47.78,1.23,22.21,0.69,1.17,0.00,...,1.218,0.025,0.046,0.000,0.000,0.611,0.892,0.106,0.000,5.164
18,sp,4,#24 - CAI,74,0.59,0.27,67.71,0.63,5.54,0.03,...,1.972,0.012,0.115,0.001,0.000,0.863,0.004,0.003,0.000,2.990
19,ol/sp,4,#24 - CAI,76,35.13,0.58,14.39,0.30,8.06,0.05,...,0.428,0.006,0.170,0.001,0.000,1.246,0.111,0.051,0.004,2.913
20,ol/sp,4,#24 - CAI,77,35.52,0.49,25.58,0.29,4.88,0.02,...,0.729,0.006,0.099,0.000,0.000,0.631,0.406,0.057,0.001,2.794
21,sp,4,#24 - CAI,84,3.24,1.36,65.06,0.08,3.05,0.01,...,1.826,0.002,0.061,0.000,0.000,0.984,0.010,0.001,0.000,2.985
22,sp,4,#24 - CAI,85,0.16,0.51,69.36,0.26,2.41,0.00,...,1.988,0.005,0.049,0.000,0.000,0.932,0.002,0.000,0.000,2.990
23,cpx,6,#24 - CAI,75,51.72,0.20,3.27,0.05,0.27,0.02,...,0.142,0.001,0.008,0.001,0.000,0.973,0.959,0.031,0.002,4.031
24,cpx,6,#24 - CAI,81,32.79,1.35,26.06,0.46,2.53,0.03,...,1.150,0.014,0.079,0.001,0.000,0.975,0.632,0.058,0.010,4.185

# <font color = brown> A complementary look into filters </font>

## Simple filter

In [70]:
fil = (df['mineral'] == 'ol') | (df['mineral'] == 'sp')
df[fil]

,mineral,oxygens,sample,no.,SiO2,TiO2,Al2O3,Cr2O3,FeO,MnO,...,Al,Cr,Fe,Mn,Ni,Mg,Ca,Na,K,total cations
0,ol,4,chd#2,1,42.51,0.04,0.07,0.04,0.18,0.00,...,0.002,0.001,0.004,0.000,0.000,1.944,0.040,0.000,0.0,2.995
1,ol,4,chd#2,9,42.16,0.10,0.06,0.20,3.14,0.07,...,0.002,0.004,0.063,0.001,0.001,1.910,0.006,0.000,0.0,2.992
10,ol,4,chd#3,15,42.72,0.05,1.08,0.11,0.37,0.01,...,0.030,0.002,0.007,0.000,0.000,1.904,0.017,0.024,0.0,2.991
11,ol,4,chd#3,17,42.83,0.03,0.11,0.16,0.45,0.00,...,0.003,0.003,0.009,0.000,0.000,1.961,0.012,0.000,0.0,2.992
12,ol,4,chd#3,18,40.43,0.02,0.03,0.11,11.16,0.00,...,0.001,0.002,0.233,0.000,0.000,1.733,0.009,0.000,0.0,2.989
13,ol,4,chd#3,21,42.46,0.05,0.27,0.10,0.32,0.03,...,0.008,0.002,0.006,0.001,0.000,1.951,0.014,0.000,0.0,2.989
18,sp,4,#24 - CAI,74,0.59,0.27,67.71,0.63,5.54,0.03,...,1.972,0.012,0.115,0.001,0.000,0.863,0.004,0.003,0.0,2.990
21,sp,4,#24 - CAI,84,3.24,1.36,65.06,0.08,3.05,0.01,...,1.826,0.002,0.061,0.000,0.000,0.984,0.010,0.001,0.0,2.985
22,sp,4,#24 - CAI,85,0.16,0.51,69.36,0.26,2.41,0.00,...,1.988,0.005,0.049,0.000,0.000,0.932,0.002,0.000,0.0,2.990

## Get the complementary data from the filter

In [71]:
df[~fil]

,mineral,oxygens,sample,no.,SiO2,TiO2,Al2O3,Cr2O3,FeO,MnO,...,Al,Cr,Fe,Mn,Ni,Mg,Ca,Na,K,total cations
2,cpx,6,chd#2,4,52.33,2.00,4.09,0.81,0.32,0.10,...,0.172,0.023,0.010,0.003,0.000,1.037,0.805,0.001,0.000,3.977
3,cpx,6,chd#2,6,51.54,1.74,5.72,0.56,0.67,0.09,...,0.241,0.016,0.020,0.003,0.000,1.019,0.795,0.003,0.000,3.984
4,opx,6,chd#2,8,57.09,0.22,0.76,0.48,1.92,0.08,...,0.031,0.013,0.055,0.002,0.001,1.897,0.025,0.001,0.000,4.002
5,opx,6,chd#2,10,59.19,0.19,0.63,0.51,0.67,0.20,...,0.025,0.014,0.019,0.006,0.001,1.906,0.024,0.001,0.000,3.988
6,cpx,6,chd#2,11,58.33,0.30,0.98,0.53,0.33,0.14,...,0.039,0.014,0.009,0.004,0.000,1.754,0.182,0.001,0.000,3.989
7,cpx,6,chd#2,12,53.87,1.10,3.09,0.51,0.21,0.08,...,0.129,0.014,0.006,0.002,0.000,1.164,0.731,0.000,0.000,3.988
8,fs,8,chd#2,3,47.10,0.06,32.39,0.01,0.21,0.00,...,1.754,0.000,0.008,0.000,0.000,0.073,0.885,0.143,0.000,5.029
9,fs,8,chd#2,5,47.72,0.06,31.87,0.01,0.71,0.03,...,1.732,0.000,0.027,0.001,0.000,0.040,0.834,0.190,0.000,5.026
14,cpx,6,chd#3,16,45.09,0.56,22.45,0.36,3.62,0.00,...,0.928,0.010,0.106,0.000,0.000,0.720,0.560,0.033,0.000,3.952
15,cpx,6,chd#3,19,46.72,1.91,22.05,0.76,0.64,0.00,...,0.922,0.021,0.019,0.000,0.001,0.388,0.742,0.034,0.000,3.837
16,fsp/mes,8,chd#3,20,46.36,0.67,27.52,0.26,0.53,0.00,...,1.516,0.010,0.021,0.000,0.005,0.330,0.947,0.053,0.000,5.073
17,fsp/mes,8,chd#3,25,47.78,1.23,22.21,0.69,1.17,0.00,...,1.218,0.025,0.046,0.000,0.000,0.611,0.892,0.106,0.000,5.164
19,ol/sp,4,#24 - CAI,76,35.13,0.58,14.39,0.30,8.06,0.05,...,0.428,0.006,0.170,0.001,0.000,1.246,0.111,0.051,0.004,2.913
20,ol/sp,4,#24 - CAI,77,35.52,0.49,25.58,0.29,4.88,0.02,...,0.729,0.006,0.099,0.000,0.000,0.631,0.406,0.057,0.001,2.794
23,cpx,6,#24 - CAI,75,51.72,0.20,3.27,0.05,0.27,0.02,...,0.142,0.001,0.008,0.001,0.000,0.973,0.959,0.031,0.002,4.031
24,cpx,6,#24 - CAI,81,32.79,1.35,26.06,0.46,2.53,0.03,...,1.150,0.014,0.079,0.001,0.000,0.975,0.632,0.058,0.010,4.185

# .isin()

In [73]:
fil = df['mineral'].isin(['ol','sp','fs'])
df.loc[fil]

,mineral,oxygens,sample,no.,SiO2,TiO2,Al2O3,Cr2O3,FeO,MnO,...,Al,Cr,Fe,Mn,Ni,Mg,Ca,Na,K,total cations
0,ol,4,chd#2,1,42.51,0.04,0.07,0.04,0.18,0.00,...,0.002,0.001,0.004,0.000,0.000,1.944,0.040,0.000,0.0,2.995
1,ol,4,chd#2,9,42.16,0.10,0.06,0.20,3.14,0.07,...,0.002,0.004,0.063,0.001,0.001,1.910,0.006,0.000,0.0,2.992
8,fs,8,chd#2,3,47.10,0.06,32.39,0.01,0.21,0.00,...,1.754,0.000,0.008,0.000,0.000,0.073,0.885,0.143,0.0,5.029
9,fs,8,chd#2,5,47.72,0.06,31.87,0.01,0.71,0.03,...,1.732,0.000,0.027,0.001,0.000,0.040,0.834,0.190,0.0,5.026
10,ol,4,chd#3,15,42.72,0.05,1.08,0.11,0.37,0.01,...,0.030,0.002,0.007,0.000,0.000,1.904,0.017,0.024,0.0,2.991
11,ol,4,chd#3,17,42.83,0.03,0.11,0.16,0.45,0.00,...,0.003,0.003,0.009,0.000,0.000,1.961,0.012,0.000,0.0,2.992
12,ol,4,chd#3,18,40.43,0.02,0.03,0.11,11.16,0.00,...,0.001,0.002,0.233,0.000,0.000,1.733,0.009,0.000,0.0,2.989
13,ol,4,chd#3,21,42.46,0.05,0.27,0.10,0.32,0.03,...,0.008,0.002,0.006,0.001,0.000,1.951,0.014,0.000,0.0,2.989
18,sp,4,#24 - CAI,74,0.59,0.27,67.71,0.63,5.54,0.03,...,1.972,0.012,0.115,0.001,0.000,0.863,0.004,0.003,0.0,2.990
21,sp,4,#24 - CAI,84,3.24,1.36,65.06,0.08,3.05,0.01,...,1.826,0.002,0.061,0.000,0.000,0.984,0.010,0.001,0.0,2.985
22,sp,4,#24 - CAI,85,0.16,0.51,69.36,0.26,2.41,0.00,...,1.988,0.005,0.049,0.000,0.000,0.932,0.002,0.000,0.0,2.990

## Select datasets that contain a specific string in a series

In [76]:
fil = df['mineral'].str.contains('fs')
df[fil]

,mineral,oxygens,sample,no.,SiO2,TiO2,Al2O3,Cr2O3,FeO,MnO,...,Al,Cr,Fe,Mn,Ni,Mg,Ca,Na,K,total cations
8,fs,8,chd#2,3,47.10,0.06,32.39,0.01,0.21,0.00,...,1.754,0.000,0.008,0.000,0.000,0.073,0.885,0.143,0.0,5.029
9,fs,8,chd#2,5,47.72,0.06,31.87,0.01,0.71,0.03,...,1.732,0.000,0.027,0.001,0.000,0.040,0.834,0.190,0.0,5.026
16,fsp/mes,8,chd#3,20,46.36,0.67,27.52,0.26,0.53,0.00,...,1.516,0.010,0.021,0.000,0.005,0.330,0.947,0.053,0.0,5.073
17,fsp/mes,8,chd#3,25,47.78,1.23,22.21,0.69,1.17,0.00,...,1.218,0.025,0.046,0.000,0.000,0.611,0.892,0.106,0.0,5.164

# <font color = brown> An additional selection of selection options</font>

## Extract specific data ( extractData() )

In [87]:
cIdf = pd.read_excel('data/chondrite element abundances.xlsx')
cIdf

,z,Element,Einheit,CI,CM,CV,CO,CK,CR,CH,H,L,LL,EH,EL,R,K
0,1,H,wt%,2.020,1.40,0.28,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,He,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Li,ppm,1.500,1.50,1.70,1.80,1.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Be,ppm,0.025,0.04,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,B,ppm,0.870,0.48,0.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,83,Bi,ppb,110.000,71.00,54.00,35.00,20.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,89,Ac,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,90,Th,ppb,29.000,41.00,58.00,80.00,58.0,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,91,Pa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,92,U,ppb,8.000,12.00,17.00,18.00,15.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
cIdf.loc[84, 'CM']

41.0

## Get the index or indices of a dataset(s)

In [90]:
cIdf['Element'] == 'Th'

0     False
1     False
2     False
3     False
4     False
      ...
82    False
83    False
84     True
85    False
86    False
Name: Element, Length: 87, dtype: bool

In [93]:
indexEl = cIdf.index[cIdf['Element'] == 'Th'][0]

cIdf.loc[indexEl, 'CM']

41.0

In [94]:
def extractData(catCol, elCol, catRow):
    indexEl = cIdf.index[cIdf[catCol] == elCol][0]
    res = cIdf.loc[indexEl, catRow]
    return res

In [101]:
extractData('Element', 'Al', 'CO')

1.4

# <font color = brown>List Operations</font>

## Count the number of identical elements

In [102]:
df['mineral'].value_counts()

cpx        8
ol         6
sp         3
fs         2
ol/sp      2
opx        2
fsp/mes    2
Name: mineral, dtype: int64

## Rename Columns

In [105]:
newNames = {'SiO2':'SiO2 (wt%)', 'TiO2':'TiO2 (wt%)'}
df.rename(columns = newNames, inplace = True)

df

,mineral,oxygens,sample,no.,SiO2 (wt%),TiO2 (wt%),Al2O3,Cr2O3,FeO,MnO,...,Al,Cr,Fe,Mn,Ni,Mg,Ca,Na,K,total cations
0,ol,4,chd#2,1,42.51,0.04,0.07,0.04,0.18,0.00,...,0.002,0.001,0.004,0.000,0.000,1.944,0.040,0.000,0.000,2.995
1,ol,4,chd#2,9,42.16,0.10,0.06,0.20,3.14,0.07,...,0.002,0.004,0.063,0.001,0.001,1.910,0.006,0.000,0.000,2.992
2,cpx,6,chd#2,4,52.33,2.00,4.09,0.81,0.32,0.10,...,0.172,0.023,0.010,0.003,0.000,1.037,0.805,0.001,0.000,3.977
3,cpx,6,chd#2,6,51.54,1.74,5.72,0.56,0.67,0.09,...,0.241,0.016,0.020,0.003,0.000,1.019,0.795,0.003,0.000,3.984
4,opx,6,chd#2,8,57.09,0.22,0.76,0.48,1.92,0.08,...,0.031,0.013,0.055,0.002,0.001,1.897,0.025,0.001,0.000,4.002
5,opx,6,chd#2,10,59.19,0.19,0.63,0.51,0.67,0.20,...,0.025,0.014,0.019,0.006,0.001,1.906,0.024,0.001,0.000,3.988
6,cpx,6,chd#2,11,58.33,0.30,0.98,0.53,0.33,0.14,...,0.039,0.014,0.009,0.004,0.000,1.754,0.182,0.001,0.000,3.989
7,cpx,6,chd#2,12,53.87,1.10,3.09,0.51,0.21,0.08,...,0.129,0.014,0.006,0.002,0.000,1.164,0.731,0.000,0.000,3.988
8,fs,8,chd#2,3,47.10,0.06,32.39,0.01,0.21,0.00,...,1.754,0.000,0.008,0.000,0.000,0.073,0.885,0.143,0.000,5.029
9,fs,8,chd#2,5,47.72,0.06,31.87,0.01,0.71,0.03,...,1.732,0.000,0.027,0.001,0.000,0.040,0.834,0.190,0.000,5.026
10,ol,4,chd#3,15,42.72,0.05,1.08,0.11,0.37,0.01,...,0.030,0.002,0.007,0.000,0.000,1.904,0.017,0.024,0.000,2.991
11,ol,4,chd#3,17,42.83,0.03,0.11,0.16,0.45,0.00,...,0.003,0.003,0.009,0.000,0.000,1.961,0.012,0.000,0.000,2.992
12,ol,4,chd#3,18,40.43,0.02,0.03,0.11,11.16,0.00,...,0.001,0.002,0.233,0.000,0.000,1.733,0.009,0.000,0.000,2.989
13,ol,4,chd#3,21,42.46,0.05,0.27,0.10,0.32,0.03,...,0.008,0.002,0.006,0.001,0.000,1.951,0.014,0.000,0.000,2.989
14,cpx,6,chd#3,16,45.09,0.56,22.45,0.36,3.62,0.00,...,0.928,0.010,0.106,0.000,0.000,0.720,0.560,0.033,0.000,3.952
15,cpx,6,chd#3,19,46.72,1.91,22.05,0.76,0.64,0.00,...,0.922,0.021,0.019,0.000,0.001,0.388,0.742,0.034,0.000,3.837
16,fsp/mes,8,chd#3,20,46.36,0.67,27.52,0.26,0.53,0.00,...,1.516,0.010,0.021,0.000,0.005,0.330,0.947,0.053,0.000,5.073
17,fsp/mes,8,chd#3,25,47.78,1.23,22.21,0.69,1.17,0.00,...,1.218,0.025,0.046,0.000,0.000,0.611,0.892,0.106,0.000,5.164
18,sp,4,#24 - CAI,74,0.59,0.27,67.71,0.63,5.54,0.03,...,1.972,0.012,0.115,0.001,0.000,0.863,0.004,0.003,0.000,2.990
19,ol/sp,4,#24 - CAI,76,35.13,0.58,14.39,0.30,8.06,0.05,...,0.428,0.006,0.170,0.001,0.000,1.246,0.111,0.051,0.004,2.913
20,ol/sp,4,#24 - CAI,77,35.52,0.49,25.58,0.29,4.88,0.02,...,0.729,0.006,0.099,0.000,0.000,0.631,0.406,0.057,0.001,2.794
21,sp,4,#24 - CAI,84,3.24,1.36,65.06,0.08,3.05,0.01,...,1.826,0.002,0.061,0.000,0.000,0.984,0.010,0.001,0.000,2.985
22,sp,4,#24 - CAI,85,0.16,0.51,69.36,0.26,2.41,0.00,...,1.988,0.005,0.049,0.000,0.000,0.932,0.002,0.000,0.000,2.990
23,cpx,6,#24 - CAI,75,51.72,0.20,3.27,0.05,0.27,0.02,...,0.142,0.001,0.008,0.001,0.000,0.973,0.959,0.031,0.002,4.031
24,cpx,6,#24 - CAI,81,32.79,1.35,26.06,0.46,2.53,0.03,...,1.150,0.014,0.079,0.001,0.000,0.975,0.632,0.058,0.010,4.185

# <font color = brown>Take everything with you</font>

## Export a dataframe

In [108]:
df.to_csv('output/test.csv', index = False)
df.to_excel('output/test.xlsx', index = False)

In [110]:
pd.read_excel('output/test.xlsx')

,mineral,oxygens,sample,no.,SiO2 (wt%),TiO2 (wt%),Al2O3,Cr2O3,FeO,MnO,...,Al,Cr,Fe,Mn,Ni,Mg,Ca,Na,K,total cations
0,ol,4,chd#2,1,42.51,0.04,0.07,0.04,0.18,0.00,...,0.002,0.001,0.004,0.000,0.000,1.944,0.040,0.000,0.000,2.995
1,ol,4,chd#2,9,42.16,0.10,0.06,0.20,3.14,0.07,...,0.002,0.004,0.063,0.001,0.001,1.910,0.006,0.000,0.000,2.992
2,cpx,6,chd#2,4,52.33,2.00,4.09,0.81,0.32,0.10,...,0.172,0.023,0.010,0.003,0.000,1.037,0.805,0.001,0.000,3.977
3,cpx,6,chd#2,6,51.54,1.74,5.72,0.56,0.67,0.09,...,0.241,0.016,0.020,0.003,0.000,1.019,0.795,0.003,0.000,3.984
4,opx,6,chd#2,8,57.09,0.22,0.76,0.48,1.92,0.08,...,0.031,0.013,0.055,0.002,0.001,1.897,0.025,0.001,0.000,4.002
5,opx,6,chd#2,10,59.19,0.19,0.63,0.51,0.67,0.20,...,0.025,0.014,0.019,0.006,0.001,1.906,0.024,0.001,0.000,3.988
6,cpx,6,chd#2,11,58.33,0.30,0.98,0.53,0.33,0.14,...,0.039,0.014,0.009,0.004,0.000,1.754,0.182,0.001,0.000,3.989
7,cpx,6,chd#2,12,53.87,1.10,3.09,0.51,0.21,0.08,...,0.129,0.014,0.006,0.002,0.000,1.164,0.731,0.000,0.000,3.988
8,fs,8,chd#2,3,47.10,0.06,32.39,0.01,0.21,0.00,...,1.754,0.000,0.008,0.000,0.000,0.073,0.885,0.143,0.000,5.029
9,fs,8,chd#2,5,47.72,0.06,31.87,0.01,0.71,0.03,...,1.732,0.000,0.027,0.001,0.000,0.040,0.834,0.190,0.000,5.026
10,ol,4,chd#3,15,42.72,0.05,1.08,0.11,0.37,0.01,...,0.030,0.002,0.007,0.000,0.000,1.904,0.017,0.024,0.000,2.991
11,ol,4,chd#3,17,42.83,0.03,0.11,0.16,0.45,0.00,...,0.003,0.003,0.009,0.000,0.000,1.961,0.012,0.000,0.000,2.992
12,ol,4,chd#3,18,40.43,0.02,0.03,0.11,11.16,0.00,...,0.001,0.002,0.233,0.000,0.000,1.733,0.009,0.000,0.000,2.989
13,ol,4,chd#3,21,42.46,0.05,0.27,0.10,0.32,0.03,...,0.008,0.002,0.006,0.001,0.000,1.951,0.014,0.000,0.000,2.989
14,cpx,6,chd#3,16,45.09,0.56,22.45,0.36,3.62,0.00,...,0.928,0.010,0.106,0.000,0.000,0.720,0.560,0.033,0.000,3.952
15,cpx,6,chd#3,19,46.72,1.91,22.05,0.76,0.64,0.00,...,0.922,0.021,0.019,0.000,0.001,0.388,0.742,0.034,0.000,3.837
16,fsp/mes,8,chd#3,20,46.36,0.67,27.52,0.26,0.53,0.00,...,1.516,0.010,0.021,0.000,0.005,0.330,0.947,0.053,0.000,5.073
17,fsp/mes,8,chd#3,25,47.78,1.23,22.21,0.69,1.17,0.00,...,1.218,0.025,0.046,0.000,0.000,0.611,0.892,0.106,0.000,5.164
18,sp,4,#24 - CAI,74,0.59,0.27,67.71,0.63,5.54,0.03,...,1.972,0.012,0.115,0.001,0.000,0.863,0.004,0.003,0.000,2.990
19,ol/sp,4,#24 - CAI,76,35.13,0.58,14.39,0.30,8.06,0.05,...,0.428,0.006,0.170,0.001,0.000,1.246,0.111,0.051,0.004,2.913
20,ol/sp,4,#24 - CAI,77,35.52,0.49,25.58,0.29,4.88,0.02,...,0.729,0.006,0.099,0.000,0.000,0.631,0.406,0.057,0.001,2.794
21,sp,4,#24 - CAI,84,3.24,1.36,65.06,0.08,3.05,0.01,...,1.826,0.002,0.061,0.000,0.000,0.984,0.010,0.001,0.000,2.985
22,sp,4,#24 - CAI,85,0.16,0.51,69.36,0.26,2.41,0.00,...,1.988,0.005,0.049,0.000,0.000,0.932,0.002,0.000,0.000,2.990
23,cpx,6,#24 - CAI,75,51.72,0.20,3.27,0.05,0.27,0.02,...,0.142,0.001,0.008,0.001,0.000,0.973,0.959,0.031,0.002,4.031
24,cpx,6,#24 - CAI,81,32.79,1.35,26.06,0.46,2.53,0.03,...,1.150,0.014,0.079,0.001,0.000,0.975,0.632,0.058,0.010,4.185